### ISSUE TITLE
v0.5 roadmap

### ISSUE THREAD

**Issue by Phlya** [open2c/cooltools#262]
#### API and CLI:
- [x] https://github.com/open2c/cooltools/issues/291 @agalitsyna 
- [x] synchronize CLI with new user-facing API functions
  - [x] consistent naming of user-facing function: no prefixes, bury modules under .api.
  - [x] consistent CLI naming: no prefixes
- [x] split expected CLI into cis and trans
- [x] discuss logbinning -> log_smoothing
- [x] split eigs-cis and eigs-trans in the CLI, its more than just a flag
- [x] include smoothing into user-facing expected-cis, update notebooks to use this

#### Code updates:
- [x] ~~several places in the code pass tuples to make_viewframe instead of lists, which is not recognized by `bioframe.from_any`.~~ `bioframe.from_any()` now supports bedframe construction from tuples
- [x] Rename regions to views, if possible (see #254)
- [x] asym expected require repeated entries in regions, which is not supported by `bioframe.make_viewframe`. This currently fails the tests of asym expected and `test_trans_saddle_cli`. see #254. 
   Options:
   - Single 1D viewframe, rewrite functions to work on all pairwise combinations of regions
   - Allow repeated entries in viewframes with an argument in `is_viewframe`
   - Migrate to 2D viewframes (requires new functions and definitions in bioframe)
- [x] In call-dots and saddle we take UCSC-named regions and expected as a requirement. Rewrite to avoid relying on that 
  - [x]  https://github.com/open2c/cooltools/blob/viewframe_update/cooltools/cli/compute_saddle.py#L325 
  - [x]   https://github.com/open2c/cooltools/blob/viewframe_update/cooltools/cli/call_dots.py#L31
- [x] Fix coverage by removing division by 2 (#255) if the cooler is upper triangular
- [x] update columns for expected to correspond to standard #217
- [x] rename to clr_weight_name #272
- [x] make saddle CLI save sums and counts separately for flexible "strength" calculation #261
- [x] restore compute-expected performance for cis-symmetric and trans-pairwise: refactor _diagsum_symm and re-introduce blocksum_pairwise #219
- [x] Distinguish user-facing / public functions vs "internal" functions, e.g. by explicit import of the former into the top namespace #258

#### Checks
- [x] checks.is_expected to validate an expected table has correct columns, dtypes, etc. https://github.com/open2c/cooltools/issues/217

#### ReFactoring
- [x] add deprecatation warning for `saddle.saddleplot` plotting from `saddle`, add it to examples for compartments and saddles
- [x] move io into contrib
- [x] move cooltools.contrast to the sandbox
- [x] move cooltools.balance to the sandbox

#### Tutorials for Open2C_examples
https://github.com/open2c/open2c_examples
- [x] contacts_vs_distance (expected)
- [x] Pileups notebook pileup_CTCF
- [x] Insulation_and_boundaries
- [x] viz
- [x] compartments and saddles
- [x] update all the notebooks pre-release

#### Documentation
- [x] expand readme and add overview
- [x] reference section (which should come after Tutorials): API reference, CLI reference, changelog
- [x] update the index page using the contents of Github's README.md. For the tutorials section also re-use the text from https://cooltools.readthedocs.io/en/latest/notebooks/README.html (delete this page afterwards, as is not linked to from anywhere in the docs and directs to tutorials on github, not in the docs)
- [x] add a link to the index page in the TOC (currently only available via the cryptic home icon above the TOC)
- [x] merge the installation page into the index 
- [x] changelog and an announcement of big changes in formats/APIs/CLIs/anything else important for users

#### Housekeeping
- [x] bump python to 3.7
- [x] bump bioframe version
- [x] https://github.com/open2c/cooltools/issues/272 @agalitsyna 
- [x] bump cooltools version

**Comment by gfudenberg** [comment]
a couple of discussion points:
- it would be good to discuss guidelines for functions in `lib.numutils` & `lib.common`: 
  - e.g. should something like saddle.mask_bad_bins` migrate to `lib.common`?
  - should functions like `saddle.digitize` and `saddle.ecdf` migrate to numutils? or become helper functions if they are only used in one modele?
- I wonder if it would benefit to split `matutils` out of `numutils`
- should checks be in `lib.checks`? or `core.checks` as in bioframe?
  - should there be a separate check for each expected schema, or one with an argument passed? 
- should `print_available_datasets` `download_file` `download_data`& related functions move somewhere like `lib.data`, `lib.io`, or `io.data`? they seem conceptually different than e.g. `assign_regions_to_bins`.

**Comment by gfudenberg** [comment]
discussion 9/15/21:
- split lib into core and contrib
- create: cooltools.contrib, a place for tools/modules that are not imported into anything else but can be potentially useful
- create cooltools.core.checks
- check if peaks is now implemented in scipy
- cython vs numba. can we drop support for cython? or is numba not stable?
- current files in io should be moved into contrib
- `print_available_datasets` download_file download_data moved to cooltools.datasets._get_test_data.py, exposed to the user via  cooltools.datasets.init.py like scikit learn: https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/datasets/__init__.py
- functions in core.numutils should not be imported into base namespace
- pure numpy functions should migrate to core.numutils, even if used in one package (e.g. `ecdf`). this could make them more visible and used across modules.
