### ISSUE TITLE
v0.5 roadmap

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooltools#312]
- [ ] set up tests/publish via Github actions!
- [ ] update track inputs to correspond to standard #271
- [ ] https://github.com/open2c/cooltools/issues/251  @Phlya @agalitsyna 
- [ ] Consider deprecating `cooltools.cli.genome` by creating bioframe CLI with these functions, or relying on cooler CLI? @nvictus #241 
- [ ] add a check for call compartments / cis_eig for the matching resolution of the phasing track and the cooler https://github.com/open2c/cooltools/issues/212
- [ ] split lib.common into core and sandbox, decide for each function where it goes
- [ ] #302
- [ ] tutorials for dots and apa
- [ ] document design choices, e.g.:
  - [ ] functions in core.numutils should not be imported into base namespace
  - [ ] pure numpy functions should be in core.numutils, even if used in one package (e.g. `ecdf()`) to make them more visible and used across modules.
  - [ ] cooltools functions should not rely on bioframe.contrib
  - [ ] main cooltools API modules and CLI should not depend on cooltools.contrib
